restore deleted restart service block

diff --git a/.ansible/playbooks/roles/django/tasks/main.yml b/.ansible/playbooks/roles/django/tasks/main.yml
--- a/.ansible/playbooks/roles/django/tasks/main.yml
+++ b/.ansible/playbooks/roles/django/tasks/main.yml
@@ -95,6 +95,28 @@
 - shell: |
     set -ex
     cd "{{cops_django_dir}}"
+    {% for i in cops_django_restarted_services.split() %}
+    has_service() { {{cops_django_dc}} config |grep -qE "^  +${1}:"; }
+    if ( has_service {{i}} );then
+    ret=
+    for i in $(seq 30);do
+      if ( {{cops_django_dc}} ps --services \
+           --filter status=running | grep -E -q "^{{i}}$");then
+        {{cops_django_dc}} up -d --no-deps --remove-orphans --force-recreate {{i}}
+        ret=$?
+      else
+        {{cops_django_dc}} up -d --no-deps --remove-orphans {{i}}
+      fi
+      if [ "x$ret" = "x0" ];then break;fi
+      sleep 1
+    done
+    if [ "x$ret" != "x0" ];then echo "{{i}}: failed restart";exit 1;fi
+    fi
+    {% endfor %}
+  tags: [django_service_restart, django_service, service]
+- shell: |
+    set -ex
+    cd "{{cops_django_dir}}"
     has_service() { {{cops_django_dc}} config |grep -qE "^  +${1}:"; }
     {% for i in cops_django_restarted_services.split()|reverse %}
     if ( has_service {{i}} );then
